# Generated by Django 4.1.3 on 2022-11-16 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "content_image",
                    models.ImageField(upload_to="history_images/content"),
                ),
                ("style_image", models.ImageField(upload_to="history_images/style")),
                ("output_image", models.ImageField(upload_to="history_images/output")),
                ("preserve_color", models.BooleanField(default=True)),
                ("nature_pattern", models.BooleanField(default=True)),
                ("alpha", models.FloatField(default=1)),
                (
                    "upload_time",
                    models.DateTimeField(
                        default=datetime.datetime(2022, 11, 17, 0, 11, 37, 419085)
                    ),
                ),
            ],
        ),
    ]
