# Generated by Django 4.1.3 on 2022-11-20 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DesignAssistant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="upload_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 20, 18, 12, 40, 223563)
            ),
        ),
    ]
