# Generated by Django 4.1.3 on 2022-11-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DesignAssistant", "0002_alter_history_upload_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="history", name="upload_time",),
    ]
